"use strict";
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
const screens={title:qs("titleScreen"),car:qs("carScreen"),stage:qs("stageScreen"),game:qs("gameScreen"),gameOver:qs("gameOverScreen")};
const scoreText=qs("scoreText"),levelText=qs("levelText"),fuelBar=qs("fuelBar"),speedText=qs("speedText"),speedBar=qs("speedBar"),shotText=qs("shotText"),shotBar=qs("shotBar"),shieldText=qs("shieldText"),finalScoreText=qs("finalScoreText"),gameOverTitle=qs("gameOverTitle"),gameOverMessage=qs("gameOverMessage");
const cars=[
{id:"kei",name:"軽自動車",description:"小さく避けやすい。燃料は少なめ。",w:38,h:58,hw:30,hh:48,acc:44,max:110,fuel:82,color:"#52e38d"},
{id:"standard",name:"普通車",description:"加速、最高速度、燃料がバランス型。初心者向け。",w:46,h:70,hw:38,hh:58,acc:42,max:120,fuel:100,color:"#5bc0ff"},
{id:"truck",name:"トラック",description:"大きく避けにくいが、燃料が多い。",w:64,h:92,hw:54,hh:80,acc:31,max:95,fuel:135,color:"#ffb84a"}
];
const stages=[
{stageName:"広島駅周辺",kind:"station",bg:"#33404a",obs:["bus","bicycle","taxi","cone","tram","dog"],rate:{fuel:.24,momiji:.26,shield:.16,slow:.16,okonomiyaki:.18},difficulty:1.15,description:"バス、自転車、タクシーが多い交通量多めのステージ。"},
{stageName:"平和記念公園周辺",kind:"park",bg:"#2f5139",obs:["tourist","bicycle","cone","dog"],rate:{fuel:.22,momiji:.32,shield:.16,slow:.16,okonomiyaki:.14},difficulty:.98,description:"観光客風の障害物が多く、アイテムがやや出やすい。"},
{stageName:"宇品港周辺",kind:"port",bg:"#294957",obs:["truck","puddle","container","cone","dog"],rate:{fuel:.30,momiji:.20,shield:.18,slow:.18,okonomiyaki:.14},difficulty:1.12,description:"トラック、水たまり、コンテナ風障害物が多い港ステージ。"},
{stageName:"宮島口周辺",kind:"tourism",bg:"#51402d",obs:["tourBus","deer","tourist","dog"],rate:{fuel:.20,momiji:.34,shield:.16,slow:.16,okonomiyaki:.14},difficulty:1.05,description:"観光バスと鹿風の障害物が登場する観光地ステージ。"},
{stageName:"マツダスタジアム周辺",kind:"stadium",bg:"#562d35",obs:["crowd","taxi","cone","bus","dog"],rate:{fuel:.18,momiji:.22,shield:.15,slow:.15,okonomiyaki:.30},difficulty:1.18,description:"赤い応援アイテムが出やすく、人混み風の障害物が多い。"}
];
const itemTypes=["fuel","momiji","shield","slow","okonomiyaki"],destroyable=new Set(["cone","bus","bicycle","tram","puddle","truck","container","tourBus","taxi"]),safe=new Set(["dog","deer","tourist","crowd"]);
let car=cars[1],stage=stages[0],screen="title",last=0,anim=0,player,obstacles,items,warnings,bullets,texts,boss,score=0,level=1,speed=0,fuel=100,maxFuel=100,shield=0,inv=0,slow=0,shot=0,obsT=0,itemT=0,dogT=0,lane=0,running=false,nextBoss=2000,bossWarn=0;
const input={left:false,right:false,up:false,down:false,accelerate:false,brake:false};
function qs(id){return document.getElementById(id)}
function show(name){screen=name;Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active")}
function buildCars(){let b=qs("carTableBody");b.innerHTML="";cars.forEach(c=>{let r=document.createElement("tr");r.innerHTML=`<td><strong>${c.name}</strong></td><td>${c.description}</td><td>${c.max} km/h</td><td>${c.fuel}</td><td><button data-car="${c.id}">この車で走る</button></td>`;b.appendChild(r)});b.querySelectorAll("button").forEach(btn=>btn.onclick=()=>{car=cars.find(c=>c.id===btn.dataset.car);show("stage")})}
function buildStages(){let list=qs("stageList");list.innerHTML="";stages.forEach((s,i)=>{let card=document.createElement("article");card.className="stage-card";card.innerHTML=`<h3>${i+1}. ${s.stageName}</h3><p>${s.description}</p><button data-stage="${i}">このステージで開始</button>`;list.appendChild(card)});list.querySelectorAll("button").forEach(btn=>btn.onclick=()=>{stage=stages[+btn.dataset.stage];start()})}
function start(){cancelAnimationFrame(anim);maxFuel=car.fuel;fuel=maxFuel;score=level=speed=shot=inv=slow=shield=obsT=0;level=1;itemT=1.2;dogT=3.5;lane=0;nextBoss=2000;bossWarn=0;boss=null;obstacles=[];items=[];warnings=[];bullets=[];texts=[];running=true;player={x:canvas.width/2-car.w/2,y:canvas.height-car.h-42,w:car.w,h:car.h,hw:car.hw,hh:car.hh,color:car.color};show("game");last=performance.now();anim=requestAnimationFrame(loop)}
function loop(t){let dt=Math.min((t-last)/1000,.04);last=t;if(running){update(dt);draw();anim=requestAnimationFrame(loop)}}
function update(dt){updateSpeed(dt);updatePlayer(dt);updateMeters(dt);spawn(dt);moveObjects(dt);moveBullets(dt);updateBoss(dt);collide();moveTexts(dt);hud()}
function updateSpeed(dt){speed+=(input.accelerate||input.up?car.acc:-10)*dt;if(input.brake||input.down)speed-=58*dt;speed=clamp(speed,0,car.max)}
function updatePlayer(dt){let ms=230+speed*1.2;if(input.left)player.x-=ms*dt;if(input.right)player.x+=ms*dt;if(input.up)player.y-=95*dt;if(input.down)player.y+=95*dt;player.x=clamp(player.x,64,canvas.width-64-player.w);player.y=clamp(player.y,boss?185:110,canvas.height-player.h-18)}
function updateMeters(dt){fuel-=(.82+speed/125)*dt;score+=(2+speed/12)*dt;level=Math.floor(score/500)+1;inv=Math.max(0,inv-dt);slow=Math.max(0,slow-dt);shot=clamp(shot+(1.4+(speed>=80?12:0)+(boss?6:0))*dt,0,100);if(fuel<=0)end("燃料切れ","燃料がなくなりました。無理せず給油も大切です。")}
function spawn(dt){let diff=stage.difficulty+level*.06,bonus=1+speed/160,bf=boss||bossWarn>0?1.7:1;obsT-=dt;itemT-=dt;dogT-=dt;if(score>=nextBoss&&!boss&&bossWarn<=0){bossWarn=1.2;text("WARNING!",240,230,"#ff554a",1.2,34);nextBoss+=2000}if(obsT<=0){spawnObstacle();obsT=Math.max(.42,1.25*bf/diff/bonus)}if(itemT<=0){spawnItem();itemT=rnd(2.2,4.4)}if(dogT<=0&&Math.random()<.72&&!boss){dogWarning();dogT=rnd(7.5,12.5)}}
function moveObjects(dt){let os=(100+speed*3.2+level*7)*(slow>0?.55:1);lane=(lane+os*dt)%90;obstacles.forEach(o=>{o.y+=os*o.sr*dt;if(o.type==="dog")o.x+=o.vx*dt});items.forEach(i=>i.y+=os*.88*dt);warnings.forEach(w=>{w.time-=dt;if(w.time<=0){obstacles.push({type:"dog",x:w.left?-34:canvas.width+8,y:w.y,w:34,h:24,vx:w.left?160:-160,sr:.35});w.done=true}});obstacles=obstacles.filter(o=>o.y<canvas.height+120&&o.x>-120&&o.x<canvas.width+120);items=items.filter(i=>i.y<canvas.height+60);warnings=warnings.filter(w=>!w.done)}
function moveBullets(dt){bullets.forEach(b=>{b.y-=620*dt;b.life-=dt});bullets=bullets.filter(b=>b.y+b.h>-20&&b.life>0)}
function updateBoss(dt){if(bossWarn>0){bossWarn-=dt;if(bossWarn<=0)boss={x:148,y:34,w:184,h:118,vx:56,hp:5,max:5,t:1.1,flash:0}}if(!boss)return;boss.x+=boss.vx*dt;if(boss.x<62||boss.x+boss.w>canvas.width-62){boss.vx*=-1;boss.x=clamp(boss.x,62,canvas.width-62-boss.w)}boss.t-=dt;boss.flash=Math.max(0,boss.flash-dt);if(boss.t<=0){let type=pick(["cone","puddle","container"]),s=size(type);obstacles.push({type,x:rnd(boss.x+12,boss.x+boss.w-s.w-12),y:boss.y+boss.h-8,w:s.w,h:s.h,sr:rnd(.9,1.2)});boss.t=Math.max(.55,1.35-speed/150-level*.02)}}
function shoot(){if(!running||screen!=="game"||shot<100)return;bullets.push({x:player.x+player.w/2-4,y:player.y-24,w:8,h:24,life:1.3});shot=0;text("SHOT!",player.x+player.w/2,player.y-22,"#9fe8ff",.45,18)}
function spawnObstacle(){let type=pick(stage.obs.filter(t=>t!=="dog")),s=size(type);obstacles.push({type,x:rnd(82,canvas.width-82-s.w),y:-s.h-10,w:s.w,h:s.h,sr:rnd(.82,1.16)})}
function dogWarning(){let left=Math.random()<.5;warnings.push({left,x:left?34:canvas.width-58,y:rnd(200,canvas.height-270),time:.85,done:false})}
function spawnItem(){let type=choose(stage.rate);items.push({type,x:rnd(86,canvas.width-118),y:-34,w:30,h:30})}
function collide(){let ph=hitbox();bulletHits();for(let o of obstacles){if(overlap(ph,o)){hitObstacle(o);return}}if(boss&&overlap(ph,bossBox())){if(inv>0)return;if(shield>0){shield--;text("SHIELD",player.x+player.w/2,player.y-16,"#9fe8ff",.6,18);return}end("ゲームオーバー","暴走トラックに接触しました。距離を取って弱点を狙いましょう。");return}items=items.filter(i=>{if(overlap(ph,i)){item(i.type);return false}return true})}
function bulletHits(){let keep=[];for(let b of bullets){let used=false;if(boss&&overlap(b,bossBox())){if(overlap(b,weakBox())){boss.hp--;boss.flash=.16;text("HIT!",boss.x+boss.w/2,boss.y+22,"#9fe8ff",.5,20);if(boss.hp<=0){score+=1000;fuel=Math.min(maxFuel,fuel+30);shield=Math.min(2,shield+1);text("BOSS CLEAR!",240,260,"#52e38d",1.4,34);boss=null}}else text("WEAK POINT!",240,180,"#ffd447",.7,18);used=true}if(!used){for(let o of obstacles){if(overlap(b,o)){if(destroyable.has(o.type)){score+=120;text("+120",o.x+o.w/2,o.y,"#9fe8ff",.6,18);obstacles=obstacles.filter(x=>x!==o)}else if(safe.has(o.type))text("危ない！",o.x+o.w/2,o.y,"#ffd447",.6,18);used=true;break}}}if(!used)keep.push(b)}bullets=keep}
function hitObstacle(o){if(inv>0){obstacles=obstacles.filter(x=>x!==o);return}if(shield>0){shield--;obstacles=obstacles.filter(x=>x!==o);text("SHIELD",player.x+player.w/2,player.y-16,"#9fe8ff",.6,18);return}if(o.type==="dog")end("安全運転に気をつけよう","犬が飛び出しました。落ち着いて周囲を確認しましょう。");else end("ゲームオーバー","障害物に接触しました。安全第一で再挑戦しましょう。")}
function item(type){if(type==="fuel"){fuel=Math.min(maxFuel,fuel+25);text("FUEL +",player.x+player.w/2,player.y-18,"#52e38d",.6,18)}if(type==="momiji"){score+=100;shot=clamp(shot+18,0,100);text("+100",player.x+player.w/2,player.y-18,"#ffd447",.6,18)}if(type==="shield"){shield=Math.min(2,shield+1);text("SHIELD",player.x+player.w/2,player.y-18,"#9fe8ff",.6,18)}if(type==="slow"){slow=5;text("SLOW",player.x+player.w/2,player.y-18,"#f8f5dc",.6,18)}if(type==="okonomiyaki"){inv=5;shot=clamp(shot+25,0,100);text("無敵",player.x+player.w/2,player.y-18,"#ff554a",.6,18)}}
function end(title,msg){if(!running)return;running=false;cancelAnimationFrame(anim);gameOverTitle.textContent=title;gameOverMessage.textContent=msg;finalScoreText.textContent=Math.floor(score);show("gameOver")}
function text(t,x,y,c="#ffd447",life=.7,sz=18){texts.push({t,x,y,c,life,max:life,sz})}
function moveTexts(dt){texts.forEach(t=>{t.life-=dt;t.y-=32*dt});texts=texts.filter(t=>t.life>0)}
function draw(){road();items.forEach(drawItem);obstacles.forEach(drawObs);warnings.forEach(drawWarn);if(boss)drawBoss();bullets.forEach(drawBullet);drawCar(player.x,player.y,player.w,player.h,player.color,car.id);meter();if(bossWarn>0)overlay();texts.forEach(drawText);if(inv>0||slow>0)effect()}
function road(){ctx.fillStyle=stage.bg;ctx.fillRect(0,0,canvas.width,canvas.height);if(bossWarn>0&&Math.floor(performance.now()/120)%2===0){ctx.fillStyle="rgba(255,85,74,.25)";ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.fillStyle="#25252c";ctx.fillRect(60,0,canvas.width-120,canvas.height);ctx.fillStyle="#1b1b21";ctx.fillRect(67,0,canvas.width-134,canvas.height);ctx.fillStyle="#e6e0be";ctx.fillRect(55,0,5,canvas.height);ctx.fillRect(canvas.width-60,0,5,canvas.height);ctx.fillStyle="#f8f5dc";for(let y=-90;y<canvas.height+90;y+=90)ctx.fillRect(canvas.width/2-5,y+lane,10,45);ctx.fillStyle="rgba(255,212,71,.18)";ctx.font="18px Arial";ctx.textAlign="left";ctx.fillText(stage.stageName,18,34)}
function drawCar(x,y,w,h,color,kind){let flash=inv>0&&Math.floor(performance.now()/120)%2===0;if(flash)return;ctx.fillStyle="rgba(0,0,0,.5)";ctx.beginPath();ctx.ellipse(x+w/2+4,y+h*.55+6,w*.68,h*.48,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0d0d12";rr(x-5,y+h*.18,10,h*.24,4);rr(x+w-5,y+h*.18,10,h*.24,4);rr(x-5,y+h*.64,10,h*.24,4);rr(x+w-5,y+h*.64,10,h*.24,4);let g=ctx.createLinearGradient(x,y,x+w,y);g.addColorStop(0,shade(color,-34));g.addColorStop(.22,shade(color,8));g.addColorStop(.5,color);g.addColorStop(.78,shade(color,10));g.addColorStop(1,shade(color,-42));ctx.fillStyle=g;rr(x,y,w,h,kind==="kei"?w*.28:w*.16);let hood=kind==="truck"?h*.2:h*.26,cabY=y+hood,cabH=kind==="truck"?h*.34:h*.35;if(kind==="truck"){ctx.fillStyle=shade(color,-18);rr(x+w*.12,y+h*.46,w*.76,h*.37,5)}ctx.fillStyle="rgba(255,255,255,.16)";rr(x+w*.14,y+5,w*.72,hood-7,4);rr(x+w*.12,cabY,w*.76,cabH,7);if(kind!=="truck")rr(x+w*.16,y+h*.72,w*.68,h*.18,4);let gg=ctx.createLinearGradient(x,cabY,x,cabY+cabH);gg.addColorStop(0,"#dff7ff");gg.addColorStop(1,"#5798b8");ctx.fillStyle=gg;rr(x+w*.19,cabY+4,w*.62,cabH*.34,4);rr(x+w*.2,cabY+cabH*.6,w*.6,cabH*.3,4);ctx.strokeStyle="rgba(20,20,25,.52)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+w/2,y+8);ctx.lineTo(x+w/2,y+h-10);ctx.stroke();ctx.fillStyle="#fff4a8";ctx.shadowColor="rgba(255,244,168,.8)";ctx.shadowBlur=8;ctx.fillRect(x+6,y+3,w*.22,5);ctx.fillRect(x+w-w*.22-6,y+3,w*.22,5);ctx.shadowBlur=0;ctx.fillStyle=kind==="truck"?"#777":"#ff4b4b";ctx.fillRect(x+7,y+h-8,w*.22,5);ctx.fillRect(x+w-w*.22-7,y+h-8,w*.22,5);if(shield>0&&x===player.x){ctx.strokeStyle="#9fe8ff";ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(x+w/2,y+h/2,w*.78,h*.62,0,0,Math.PI*2);ctx.stroke()}}
function drawBoss(){vehicle(boss.x,boss.y,boss.w,boss.h,boss.flash>0?"#fff":"#8c8c8c",10);ctx.fillStyle="#4e4e55";rr(boss.x+20,boss.y+44,boss.w-40,46,5);ctx.fillStyle="#dff7ff";rr(boss.x+38,boss.y+16,boss.w-76,22,5);let w=weakBox();ctx.fillStyle=Math.floor(performance.now()/150)%2?"#ff554a":"#ffd447";ctx.beginPath();ctx.arc(w.x+w.w/2,w.y+w.h/2,w.w/2,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="rgba(0,0,0,.75)";ctx.fillRect(110,12,260,16);ctx.fillStyle="#ff554a";ctx.fillRect(112,14,256*(boss.hp/boss.max),12);ctx.fillStyle="#f8f5dc";ctx.font="bold 13px Arial";ctx.textAlign="center";ctx.fillText("BOSS HP",240,26)}
function drawObs(o){let c={cone:"#ff7a2f",bus:"#4fc3ff",tourBus:"#ffd447",taxi:"#f2c94c",bicycle:"#f8f5dc",tram:"#72d6a0",puddle:"#55bde8",truck:"#b8b8b8",container:"#b65042",tourist:"#ff554a",crowd:"#ff554a",deer:"#b8793f",dog:"#9a6338"}[o.type]||"#d65f3d";if(["bus","tourBus","taxi","truck"].includes(o.type))vehicle(o.x,o.y,o.w,o.h,c,7);else if(o.type==="puddle"){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(o.x+o.w/2,o.y+o.h/2,o.w/2,o.h/2,0,0,Math.PI*2);ctx.fill()}else if(o.type==="cone"){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(o.x+o.w/2,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.lineTo(o.x,o.y+o.h);ctx.closePath();ctx.fill();ctx.fillStyle="#f8f5dc";ctx.fillRect(o.x+6,o.y+o.h*.55,o.w-12,5)}else if(o.type==="dog"){ctx.fillStyle=c;ctx.fillRect(o.x+6,o.y+7,o.w-12,o.h-8);ctx.fillRect(o.x+o.w-12,o.y+2,10,11);ctx.fillStyle="#111";ctx.fillRect(o.x+o.w-5,o.y+6,3,3)}else if(o.type==="deer"){ctx.fillStyle=c;ctx.fillRect(o.x+8,o.y+12,o.w-12,o.h-18);ctx.fillRect(o.x+o.w-12,o.y+4,12,14)}else if(["tourist","crowd"].includes(o.type)){for(let i=0;i<(o.type==="crowd"?4:2);i++){let px=o.x+8+i*12;ctx.fillStyle=i%2?"#ffd447":"#ff554a";ctx.beginPath();ctx.arc(px,o.y+8,5,0,Math.PI*2);ctx.fill();ctx.fillRect(px-4,o.y+15,8,o.h-18)}}else box(o.x,o.y,o.w,o.h,c)}
function drawItem(i){ctx.save();ctx.translate(i.x+i.w/2,i.y+i.h/2);if(i.type==="fuel"){ctx.fillStyle="#52e38d";ctx.fillRect(-10,-13,20,26);ctx.fillStyle="#17171c";ctx.fillRect(-5,-8,10,7)}if(i.type==="momiji"){ctx.fillStyle="#ff554a";for(let n=0;n<5;n++){ctx.rotate(Math.PI*2/5);ctx.fillRect(-4,-14,8,14)}}if(i.type==="shield"){ctx.strokeStyle="#9fe8ff";ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,13,0,Math.PI*2);ctx.stroke()}if(i.type==="slow"){ctx.fillStyle="#f8f5dc";ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#17171c";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-9);ctx.moveTo(0,0);ctx.lineTo(8,5);ctx.stroke()}if(i.type==="okonomiyaki"){ctx.fillStyle="#c98745";ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f8f5dc";ctx.fillRect(-10,-2,20,4);ctx.fillStyle="#ff554a";ctx.fillRect(-6,-8,12,3)}ctx.restore()}
function drawWarn(w){ctx.fillStyle="#ffd447";ctx.fillRect(w.x,w.y-10,26,34);ctx.fillStyle="#17171c";ctx.font="bold 28px Arial";ctx.textAlign="left";ctx.fillText("!",w.x+8,w.y+17)}
function drawBullet(b){ctx.save();ctx.shadowColor="#9fe8ff";ctx.shadowBlur=14;ctx.fillStyle="#dff7ff";rr(b.x,b.y,b.w,b.h,4);ctx.restore()}
function overlay(){ctx.fillStyle="rgba(0,0,0,.5)";ctx.fillRect(70,350,canvas.width-140,82);ctx.fillStyle="#ff554a";ctx.font="bold 36px Arial";ctx.textAlign="center";ctx.fillText("WARNING!",240,402)}
function effect(){ctx.fillStyle="rgba(0,0,0,.55)";ctx.fillRect(100,72,canvas.width-200,50);ctx.fillStyle="#ffd447";ctx.font="bold 18px Arial";ctx.textAlign="center";ctx.fillText([inv>0?"無敵":"",slow>0?"スロー":""].filter(Boolean).join(" / "),240,104)}
function meter(){let x=404,y=canvas.height-78,r=48,rate=speed/car.max,a=Math.PI*.9+(Math.PI*1.2)*rate;ctx.fillStyle="rgba(0,0,0,.52)";ctx.beginPath();ctx.arc(x,y,r,Math.PI,0);ctx.fill();ctx.strokeStyle="#f8f5dc";ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r,Math.PI*.9,Math.PI*2.1);ctx.stroke();ctx.strokeStyle="#ff554a";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*34,y+Math.sin(a)*34);ctx.stroke();ctx.fillStyle="#f8f5dc";ctx.font="bold 13px Arial";ctx.textAlign="center";ctx.fillText(`${Math.floor(speed)}`,x,y-8);ctx.font="10px Arial";ctx.fillText("km/h",x,y+7)}
function drawText(t){ctx.save();ctx.globalAlpha=clamp(t.life/t.max,0,1);ctx.fillStyle=t.c;ctx.font=`bold ${t.sz}px Arial`;ctx.textAlign="center";ctx.shadowColor="#000";ctx.shadowBlur=4;ctx.fillText(t.t,t.x,t.y);ctx.restore()}
function vehicle(x,y,w,h,c,r){ctx.fillStyle="rgba(0,0,0,.45)";rr(x+4,y+4,w,h,r);ctx.fillStyle="#111";rr(x-3,y+h*.18,7,h*.22,3);rr(x+w-4,y+h*.18,7,h*.22,3);rr(x-3,y+h*.66,7,h*.22,3);rr(x+w-4,y+h*.66,7,h*.22,3);let g=ctx.createLinearGradient(x,y,x+w,y);g.addColorStop(0,shade(c,-22));g.addColorStop(.5,c);g.addColorStop(1,shade(c,-32));ctx.fillStyle=g;rr(x,y,w,h,r);ctx.fillStyle="rgba(255,255,255,.16)";rr(x+6,y+5,w-12,h*.22,4)}
function rr(x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();ctx.fill()}
function box(x,y,w,h,c){ctx.fillStyle="#111";ctx.fillRect(x+4,y+4,w,h);ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function hitbox(){return{x:player.x+(player.w-player.hw)/2,y:player.y+(player.h-player.hh)/2,w:player.hw,h:player.hh}}
function bossBox(){return boss?{x:boss.x+12,y:boss.y+10,w:boss.w-24,h:boss.h-18}:{x:0,y:0,w:0,h:0}}
function weakBox(){return boss?{x:boss.x+boss.w/2-18,y:boss.y+74,w:36,h:36}:{x:0,y:0,w:0,h:0}}
function size(t){return{cone:{w:28,h:34},bus:{w:58,h:82},taxi:{w:46,h:66},bicycle:{w:38,h:42},tram:{w:54,h:98},puddle:{w:60,h:28},truck:{w:62,h:92},container:{w:64,h:48},tourist:{w:38,h:48},crowd:{w:60,h:48},deer:{w:44,h:34},tourBus:{w:64,h:88}}[t]||{w:42,h:42}}
function choose(rate){let total=itemTypes.reduce((s,t)=>s+rate[t],0),v=Math.random()*total;for(let t of itemTypes){v-=rate[t];if(v<=0)return t}return"momiji"}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function shade(color,p){let h=color.replace("#",""),n=Math.round(2.55*p),r=clamp(parseInt(h.slice(0,2),16)+n,0,255),g=clamp(parseInt(h.slice(2,4),16)+n,0,255),b=clamp(parseInt(h.slice(4,6),16)+n,0,255);return`rgb(${r}, ${g}, ${b})`}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function rnd(a,b){return Math.random()*(b-a)+a}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hud(){scoreText.textContent=Math.floor(score);levelText.textContent=level;fuelBar.style.width=`${clamp(fuel/maxFuel*100,0,100)}%`;speedText.textContent=`${Math.floor(speed)} km/h`;speedBar.style.width=`${clamp(speed/car.max*100,0,100)}%`;shotText.textContent=shot>=100?"SHOT OK":`${Math.floor(shot)}%`;shotBar.style.width=`${clamp(shot,0,100)}%`;shieldText.textContent=shield>0?`${shield}回`:"なし"}
window.addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();if(!e.repeat)shoot();return}setKey(e.key,true)});window.addEventListener("keyup",e=>setKey(e.key,false));
function setKey(k,p){if(k==="ArrowLeft"||k.toLowerCase()==="a")input.left=p;if(k==="ArrowRight"||k.toLowerCase()==="d")input.right=p;if(k==="ArrowUp"||k.toLowerCase()==="w"){input.up=p;input.accelerate=p}if(k==="ArrowDown"||k.toLowerCase()==="s"){input.down=p;input.brake=p}}
document.querySelectorAll("#touchControls button[data-key]").forEach(btn=>{let k=btn.dataset.key;btn.addEventListener("pointerdown",e=>{e.preventDefault();input[k]=true;btn.setPointerCapture(e.pointerId)});["pointerup","pointercancel","pointerleave"].forEach(ev=>btn.addEventListener(ev,()=>input[k]=false))});document.querySelectorAll("#touchControls button[data-action='shoot']").forEach(btn=>btn.addEventListener("pointerdown",e=>{e.preventDefault();shoot()}));
qs("startButton").onclick=()=>show("car");qs("retryButton").onclick=start;qs("backToCarButton").onclick=()=>show("car");document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>show(b.dataset.screen.replace("Screen","")));buildCars();buildStages();hud();
